{"ClassRef":{"value":"500000000001619418","name":"24:54 CXFS"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"566582","name":"25:07 CXS"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"578353","name":"25:54 CXFS"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"575219","name":"25:47 FPM"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"570673","name":"25:10 DMFS TO"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"624485","name":"26:01 FENI"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"600308","name":"25:49 DAPS"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}{"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"529974","name":"25:35 DMFS West"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"568813","name":"25:33 DMFS NY"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"549129","name":"25:50 DMFS MW"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"587612","name":"25:44 EX"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"523347","name":"25:17 BD"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"571637","name":"25:32 DCX"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}
{"ClassRef":{"value":"578355","name":"25:25 MA"},"AccountRef":{"value":"356","name":"5010 Direct Costs:Marketing:Desktop Publishing / Design"},"BillableStatus":"NotBillable","TaxCodeRef":{"value":"5"}}