module.exports = {
    invoice: [
      'invoice_number',
      'invoice_date',
      'currency',
      'customer_name',
      'amount_cad'
    ],
    payment: [
      'supplier_invoices',
      'payment_date',
      'currency',
      'detail',
      // 'amount_cad',
      'vendor_name',
      'amount'
    ],
    ap: [
      'date',
      'transaction_type',
      'invoice_number',
      'supplier',
      'due_date',
      'past_due',
      'amount',
      'open_balance',
      'foreign_amount',
      'foreign_open_balance',
      'currency',
      'exchange_rate'
    ],
    ar: [
      'date',
      'transaction_type',
      'invoice_number',
      'customer',
      'due_date',
      'amount',
      'open_balance',
      'foreign_amount',
      'foreign_open_balance',
      'currency',
      'exchange_rate'
    ],
    closed_deal:[
      'amount',
      'amount_in_home_currency',
      'closedate',
      'hs_closed_amount',
      'dealname',
      'dealtype',
      // 'hubspot_owner_id',
      'initial_traffic_source',
      'traffic_source_detail_or_entry_point',
      // 'hs_analytics_source_data_2',
      'company_name',
      'conference_code',
      'conference_internal_name',
      'hs_is_closed_won',
      'hubspot_owner_name'
    ],
    lead:[
      'amount',
      'amount_in_home_currency',
      // 'closedate',
      'hs_closed_amount',
      'hs_closed_amount_in_home_currency',
      'createdate', //add new
      'days_to_close',
      // 'description',
      'dealname',	
      'dealtype',
      'notes_last_updated',
      'notes_last_contacted',	
      'num_notes',	
      'initial_traffic_source',
      'traffic_source_detail_or_entry_point',
      // 'hs_analytics_source_data_2',	
      'hs_sales_email_last_replied',
      'conference_code',	
      'company_name',	
      'conference_group',
      'conference_internal_name',	
      // 'deal_age',	
      'hs_is_closed_won',	
      'hubspot_owner_name',	
      'dealstage_name'										
    ]
  
  };